name: Notify

on:
  workflow_run:
    workflows: ["schedule"]
    types:
      - completed

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.head_branch == 'main' }}

    steps:
      - uses: 1password/load-secrets-action@v3
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          SLACK_BOT_TOKEN: op://Developer/GitHub Actions Slack Bot/credential

      - uses: slackapi/slack-github-action@v2
        with:
          method: chat.postMessage
          token: ${{ env.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "${{ vars.SLACK_CHANNEL_ID }}",
              "text": "The `${{ github.event.workflow_run.name }}` workflow failed on `${{ github.event.workflow_run.head_branch }}` in <${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>!",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":warning: The `${{ github.event.workflow_run.name }}` workflow failed on `${{ github.event.workflow_run.head_branch }}` in <${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>.\n\n:github: <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.event.workflow_run.head_sha }}|Committed> by _${{ github.event.workflow_run.head_commit.author.name }}_ at `${{ github.event.workflow_run.head_commit.timestamp }}`."
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": ":wood: View job logs"
                    },
                    "url": "${{ github.event.workflow_run.html_url }}"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Edit this message <${{ github.server_url }}/${{ github.repository }}/blob/main/.github/workflows/notify.yaml|here>."
                    }
                  ]
                }
              ]
            }
